package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pei Wang
 */
public class LinksView extends javax.swing.JFrame {

    /**
     * Creates new form LinksView
     */
    public LinksView() {
        initComponents();
        
        but_visit.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				int row = link_table.getSelectedRow();
				if(row!=-1){
					String uri = ""+link_table.getModel().getValueAt(row, 1); 
					openURI(uri);
				}
			}
        	
        });
        
        but_back.addActionListener(new ActionListener(){

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				close();
			}     	
        });
        
    }
    private void close(){
		this.dispose();
    	
    }
    
    private void openURI(String uri){
		try {
			URI url = new URI(uri);
			java.awt.Desktop.getDesktop().browse(url);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LayeredPane = new javax.swing.JLayeredPane();
        LinksView_front = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        link_table = new javax.swing.JTable();
        LinksView_back = new javax.swing.JLabel();
        but_visit = new javax.swing.JButton();
        but_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(640, 425));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LayeredPane.setBackground(new java.awt.Color(255, 255, 255));

        LinksView_front.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        LinksView_front.setText("Links");
        LinksView_front.setBounds(20, 10, 210, 40);
        LayeredPane.add(LinksView_front, javax.swing.JLayeredPane.DEFAULT_LAYER);

        link_table.setModel(new javax.swing.table.DefaultTableModel(
            links,
            new String [] {
                "Name", "Address"
            }
        ));
        jScrollPane1.setViewportView(link_table);

        jScrollPane1.setBounds(10, 50, 590, 250);
        LayeredPane.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LinksView_back.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        LinksView_back.setForeground(new java.awt.Color(204, 204, 204));
        LinksView_back.setText("Links");
        LinksView_back.setBounds(10, 20, 340, 50);
        LayeredPane.add(LinksView_back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        but_visit.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        but_visit.setText("Visit");
        but_visit.setBounds(310, 320, 130, 31);
        LayeredPane.add(but_visit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        but_back.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        but_back.setText("Back");
        but_back.setBounds(450, 320, 130, 31);
        LayeredPane.add(but_back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LayeredPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LayeredPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinksView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinksView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinksView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinksView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinksView().setVisible(true);
            }
        });
    }
    
    private String [][] links = new String [][] {
    		{"UNSW ASB", "https://www.asb.unsw.edu.au"},
            {"UNSW Blackboard", "https://student.unsw.edu.au/blackboard"},
            {"Tech Support", "mailto:adagetradingsimulator@gmail.com"}
        };
    // Variables declaration - do not modify                     
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_visit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable link_table;
    private javax.swing.JLabel LinksView_back;
    private javax.swing.JLabel LinksView_front;
    // End of variables declaration                   
}
