package view;
public class PortfolioView extends javax.swing.JFrame {

    /**
     * Creates new form Portfolio
     */
    public PortfolioView(float sc) {
    	startingCash = sc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LayeredPane = new javax.swing.JLayeredPane();
        portfolio_front = new javax.swing.JLabel();
        Tabbs_pane = new javax.swing.JTabbedPane();
        Orders_pane = new javax.swing.JPanel();
        Order_scroll = new javax.swing.JScrollPane();
        Orders_table = new javax.swing.JTable();
        but_neworder = new javax.swing.JButton();
        but_cancelorder = new javax.swing.JButton();
        Onhand_pane = new javax.swing.JPanel();
        Onhand_scroll = new javax.swing.JScrollPane();
        Onahnd_table = new javax.swing.JTable();
        but_sellonhand = new javax.swing.JButton();
        History_pane = new javax.swing.JPanel();
        history_scroll = new javax.swing.JScrollPane();
        history_table = new javax.swing.JTable();
        portfolio_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LayeredPane.setBackground(new java.awt.Color(255, 255, 255));

        portfolio_front.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        portfolio_front.setText("Portfolio");
        portfolio_front.setBounds(20, 10, 210, 40);
        LayeredPane.add(portfolio_front, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Orders_pane.setBackground(new java.awt.Color(255, 255, 255));

        Orders_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Order_scroll.setViewportView(Orders_table);

        but_neworder.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        but_neworder.setText("New Order");
        but_neworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_neworderActionPerformed(evt);
            }
        });

        but_cancelorder.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        but_cancelorder.setText("Cancel Order");

        javax.swing.GroupLayout Orders_paneLayout = new javax.swing.GroupLayout(Orders_pane);
        Orders_pane.setLayout(Orders_paneLayout);
        Orders_paneLayout.setHorizontalGroup(
            Orders_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Order_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Orders_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_neworder, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(but_cancelorder, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        Orders_paneLayout.setVerticalGroup(
            Orders_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Orders_paneLayout.createSequentialGroup()
                .addComponent(Order_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Orders_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_cancelorder, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(but_neworder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Tabbs_pane.addTab("Orders", Orders_pane);

        Onhand_pane.setBackground(new java.awt.Color(255, 255, 255));

        Onahnd_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Onhand_scroll.setViewportView(Onahnd_table);

        but_sellonhand.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        but_sellonhand.setText("Sell Onhand");

        javax.swing.GroupLayout Onhand_paneLayout = new javax.swing.GroupLayout(Onhand_pane);
        Onhand_pane.setLayout(Onhand_paneLayout);
        Onhand_paneLayout.setHorizontalGroup(
            Onhand_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Onhand_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Onhand_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_sellonhand, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        Onhand_paneLayout.setVerticalGroup(
            Onhand_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Onhand_paneLayout.createSequentialGroup()
                .addComponent(Onhand_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_sellonhand, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabbs_pane.addTab("Onhand", Onhand_pane);

        History_pane.setBackground(new java.awt.Color(255, 255, 255));

        history_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        history_scroll.setViewportView(history_table);

        javax.swing.GroupLayout History_paneLayout = new javax.swing.GroupLayout(History_pane);
        History_pane.setLayout(History_paneLayout);
        History_paneLayout.setHorizontalGroup(
            History_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(history_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        History_paneLayout.setVerticalGroup(
            History_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(History_paneLayout.createSequentialGroup()
                .addComponent(history_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        Tabbs_pane.addTab("History Action", History_pane);

        Tabbs_pane.setBounds(20, 50, 630, 400);
        LayeredPane.add(Tabbs_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        portfolio_back.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        portfolio_back.setForeground(new java.awt.Color(204, 204, 204));
        portfolio_back.setText("Portfolio");
        portfolio_back.setBounds(10, 20, 340, 50);
        LayeredPane.add(portfolio_back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void but_neworderActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortfolioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortfolioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortfolioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortfolioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortfolioView(10000).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify 
    
    private float startingCash;
    
    private javax.swing.JPanel History_pane;
    private javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JTable Onahnd_table;
    private javax.swing.JPanel Onhand_pane;
    private javax.swing.JScrollPane Onhand_scroll;
    private javax.swing.JScrollPane Order_scroll;
    private javax.swing.JPanel Orders_pane;
    private javax.swing.JTable Orders_table;
    private javax.swing.JTabbedPane Tabbs_pane;
    private javax.swing.JButton but_cancelorder;
    private javax.swing.JButton but_neworder;
    private javax.swing.JButton but_sellonhand;
    private javax.swing.JScrollPane history_scroll;
    private javax.swing.JTable history_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel portfolio_back;
    private javax.swing.JLabel portfolio_front;
    // End of variables declaration                   
}
